sudo: false
language: python
python:
- '3.4'
env:
- TEST_SUITE='coverage run --source=pyega3 setup.py test'
install:
- pip install -r requirements.txt
- pip install python-coveralls
script:
- echo $TEST_SUITE
- echo $TEST_SUITE > test.sh
- bash test.sh
after_success:
- coverage report
- coveralls
- python setup.py sdist
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: ega
  password:
    secure: XvVVuy398xAHwuRjyVcL+RlqUu2vDOGVOoNgahKn7ipe7EFvCnX+4rtgZn7XWIB+zjEaMk1E3A+Ql9PAWhIlrxidMY+izGyOaDZ5JI2YXTQ3YF6wBmplxXYwp8f3+4UYbv5pJzJEXRJv4geCSEnjM0VtMofmxuxT0sD5HYhLHus6+8uYtm5ipNZom1ZcW16CTa9mus3BxCZja4i5mduZG64ZKE3mQkyHruo3Dxst8PW5KVa8aq6hMqdxtvwOT8bv5lsf/JwAMdvn3Bsqz3MUEwAdIH02yj0BlgmNAPRCSmwJhhITOO+NbMdG4drxcymIa6EwaboRtn/GWTvrHw7hTn1EVFohflQRBkfz0CDY2Pah80c3YZOqbUTZLIPSN2ZR4/YuYzW/11E6y2SWvRjWpS/VEiViUsbxkUWpUER3kDb7/srhu+C0SZcxnf3Wj7dZMRne1e2htV5ysdvsSzqi0vPnz9YJPJ66WSfDdcmF0GZrhC+VzfqKJ8uQePX+rtScJL0breC+zInZZV+0HuyYSB6IbEwgLNNgEk6rtEXXQXKAXerLMsqkIdSrGJjKqwewysInNpcd1UDwwE61Tfh6eNV7EY2YhQZnV6vyBpCtvCJ6t4zDcfq4Up5b1MWQw89VkUAlWnFFJX7wJlysqnuW9DPZDtiMq8nJCYmJAYttp9A=
  on:
    tags: true
