sudo: false
language: python
python:
    - "3.4"
env: 
    - TEST_SUITE='coverage run --source=pyega3 setup.py test'
install: 
    - pip install -r requirements.txt
    - pip install python-coveralls
script: 
    - echo $TEST_SUITE
    - echo $TEST_SUITE > test.sh
    - bash test.sh
after_success: 
    - coverage report
    - coveralls
    - python setup.py sdist
    - twine upload --repository-url https://test.pypi.org/legacy/ dist/*
