sudo: false
language: python
python:
- '3.4'
env:
- TEST_SUITE='coverage run --source=pyega3 setup.py test'
install:
- pip install -r requirements.txt
- pip install python-coveralls
script:
- echo $TEST_SUITE
- echo $TEST_SUITE > test.sh
- bash test.sh
after_success:
- coverage report
- coveralls
- python setup.py sdist
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: ega
  password:
    secure: MoyEs5k2IMytrQ2GT912KlSjHYPNlCaBcKojhOpONfLEdlL249woMJovdlh9otSZ4lg0NRKof4xlgdubZck/uBmPL1QwgOEmUfTmMKezNPU0+PfrxLGuMudqwJIgxAMgN3ASOvzSyhMMsB/IRLzBwhjVN1LokDw1yvPKTMDmUp+RReDqrWIEXoucOe+WPw1SUGcEW1fkftP8AagLdlPxhOxMZJ1ZUxBWUmtgWqJny2OtrlVfpkRVGRBFGtHCznXBN7YizOzGbFw2p7AtYbz2EGqIdkTx0miCcdqDgd+hxRiq78p+k82biraYX9rO3BCS6oFeqW79GvzZ153uyqladH4UkAJfumDyAN5QPG0wfBQJeUGHKHOmQErP4IH9+0UvfQHgA7M/mrfNIE7zNTrxqPTMlX6Nu+rycy2fFNUyZpczScQn15GViPhbkvxd7Srmc6Zl8t1xKnDLIQumqdGkM0kZenx74kC0fC+wh2UfkDX+rUYaz/6vI5ckqVgGSFUpVfTL6vpZlZDk1rcY/3fYKHaBUZfNTYTEZlb/8a2OEU/fbwxppBUKMagvl8YDZoiSDr4OQz0Tp/X8b9EO5RE8dk+B3mpgcGNRSRc8YxrzDiuz1k3T5/1Qj4VG/WvE512Fk1p+JehK/UNZ+2dA/lz7GvmrZKhtqcbcFmHhd+X7GFc=
  on:
    tags: true
