sudo: false
language: python
python:
- '3.4'
env:
- TEST_SUITE='coverage run --source=pyega3 setup.py test'
install:
- pip install -r requirements.txt
- pip install python-coveralls
script:
- echo $TEST_SUITE
- echo $TEST_SUITE > test.sh
- bash test.sh
after_success:
- coverage report
- coveralls
- python setup.py sdist
deploy:
  provider: pypi
  user: ega-bot
  password:
    secure: sJyAZ8D9MqvCkwmg4CKbfTO1G5JNYg6yHVcFAhEWFxke89wex5KtvO6wu23kaq8bqkYmyd42mh8L23xioAPMsrOyK3wIJboG70ymFOlNlTL5V0BhdPRwUekfjwRy2Ph9L4dJRaiqpHZoK8Hjm5ght1oHtrwPiKhJIUxWC1CykSgI/B+Nsd2i2rM/i9FknFomh0W5iJYYR6hbare8SZEf4ydxGaxUQBV3zn6poK3byFZwKpIrVGI98SxkSQwZORaljIyUFuPVvL6sDXWDnpkFaYpcbgX8sHE4XTqJjyiQ1SAOrEY+mUHQT0OfGd4vUUo4NSBzSwHdZXzA/cr6aYSSoQaqKj9KtE/aGwohTdgXxn0q328Qp8yvGMYZ3dGm0ev/Go+DflgJpzmOLPfKN19C997FrQDJzFO3jehz9YFk6qgfSaDDi3K8KuDunnt3ifEkm0Nd0M4enMVy8Z83ietob/mDt5tiHmQoZcrwjCnNiuULwVLDQ/96TnECcicJ3tZ+b9tjHT6RGhgIHVhALL2aZ5W973ug3C675gVR9gp5H0mtsNU7CCHqQLUQLphnNypYTB7Bd6lK/NLkLlOf0Pisrd9osm+09v1YZw3Bd3HrDvKGL2mtSJsQ0gmioaXo/dY8JiQDdZom8Fde95/qi/njkImJR06T1AwUYJ41j/UUE9g=
  on:
    tags: true
