sudo: false
language: python
python:
- '3.4'
env:
- TEST_SUITE='coverage run --source=pyega3 setup.py test'
install:
- pip install -r requirements.txt
- pip install python-coveralls
script:
- echo $TEST_SUITE
- echo $TEST_SUITE > test.sh
- bash test.sh
after_success:
- coverage report
- coveralls
- python setup.py sdist
deploy:
  provider: pypi
  user: EGA-archive
  password:
    secure: 0yxfl13EoHHG+uJxiSz0lYiMScKLQyOfnY+h8iDKMVieBYpUs+W7O6hezuOpyzs1sA/iOrFU9oeeHVpwrhQlNchUQRKBfKdR9p0c2wIVBVPQkBxMUi59gvxmikmhzXzNdBF/Wod9P99T5zhiUjA8XUqSvyxgyQGyMZTlCUJMKtvIvm1fxE8p5GU7KQbKFFFipzROD0W6v+igL9Ot1Gc/rL6EJ8uz4G/Ipu6fi53RUVZRnb2td58E5xee1u/Vuw7jocsI6tjK05CLI8+AmV3ugf00loJEd6yULl/DUwSp5JKmcgcS/ceaNRN1pycMAgDKnqOkwtZfs8MOONukNpF3AgGGZP/FIGJ4tAhwTHZ/5sMCUvpiO4LGR+G8x+9rJk36AkQkLInNEOhcs/1/3fuuAbCkWq4IR83lD7wzEUZnIh/Gjrbqr/p2lQacnQojbfRmqAaroasbc6sIaF8rENfv9Q27Kb/GW4NKw8zsNTWA8IwQfQgVb+emkJJ71spnCQ8uBOA8BcsEsbkIKGmIByPTgok9kYbW6x6OsTFBnvWIC7QV9ZbCaZFPPgLncFKGMUZ+wfHaG/DGA00EnE8audxk+c05YC/SyN4yo2FdxS6MaG/YXmWuwVAG1a9cws1X0bYF0nXeZp+7uuKKsBVHcdsEomXBj9eFBhmLT/394aVapwE=
  on:
    tags: true
