sudo: false
language: python
python:
- '3.4'
env:
- TEST_SUITE='coverage run --source=pyega3 setup.py test'
install:
- pip install -r requirements.txt
- pip install python-coveralls
script:
- echo $TEST_SUITE
- echo $TEST_SUITE > test.sh
- bash test.sh
after_success:
- coverage report
- coveralls
- python setup.py sdist
deploy:
  provider: pypi
  user: ega-bot
  password:
    secure: A26xBV+p9mwjy0To+kl/oXxFHbgJBQPKFjiCRtLl4lR6KVSRKSnVu+n4L+GlYIOuE8rJM7PgtGgFqp644ZZuQGK+GmVGkJXBBJzAi3Znxc/mMS6K7tYQpdU/EtMShIyxxS6YESciqszjw0V8scjyUl4fSzzMRp25mxYFrK1ycZkrit6UI6/wAxD2VR0cigSLkYW4mSzedjuX3+D554VCAgqxR3N29UuJsp+847IZCmHXYZJv1vuWsxTSOUWCBUPUGYJAhTczJOfNs9CbbgQTPpjurF1KyI/bqRU0Gs+2NlbW4hPM5D08OuQCxWifBvyDaQe3WnVBjTyjJaQHgUrI+qgD+8O02cOQFG4iUFFnA+IVCrM0IjwU43mmxWUd1OOrkhG9RElBv1cCBLbyXPZHMEck267K4SFy9g74pDTb7a9XE6yIgAlHIZZ3kfxwmti3sGua4ugLF46h1SJ0eVYue9JZ3lwdLsI60rDlp2GXat17u1AXcLpFm5on/LmgpMlnVCn1PXcc/5FFEmMiUb7JzjSWDyXVu2YlZ/v/MmzLeAPRjWGzsIJalKDt96mNa1meirpG5kZoBF4CRtIcHTDlaYuELa3E1Mt1weGOvnweMNI+jgbP5V7DvaakbXIwUxdQCtIs0YMxVrqgBhZmTlbxCcRAX0lOSmigHOaNtk+HC/A=
  on:
    tags: true
