sudo: false
language: python
python:
- '3.4'
env:
- TEST_SUITE='coverage run --source=pyega3 setup.py test'
install:
- pip install -r requirements.txt
- pip install python-coveralls
script:
- echo $TEST_SUITE
- echo $TEST_SUITE > test.sh
- bash test.sh
after_success:
- coverage report
- coveralls
- python setup.py sdist
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: ega
  password:
    secure: nR+FGbxOxvwp3P5zyOqRubelOarD3gwHn9zMSmUceSLOVfcxnWMi+8FaB77d7QJrKxQx07K7mlvV+rJGve5zWMgu1M74pVpW7q3tacIggMGNkybBKoM7NP5ZN8+gtcw5ttSTRGkc5VdtRU9zV6sUvp3SMj2k4B5AwpA86A67NaTiQdjz6CDHqjA1ysO90JqeiyUcS1VYyF/38z5bQqIoL7Y1BUPUMz3Kj5nuTpXfFxcDuIeSxpCv3Pao8YYHTo6UJFFMsMn2L5WMf+oDO3cmiHQI2+VPVnIG2HZjO6DobTa1qmZkKDWelsGz5DtG24DUm0XrE6dzFbIFo6cnosEkg30hkOOTyQQlugq4Oz0xksUETlRs7U9I0Fot3kj3kjR0jUxIC5OLzl6OQlbgVifXEJxefgmQ/x8FKFLH0x4u07x1Er9ea0skoR6CargRf3knBkdNX1zeWx48GvoOyesbx+e6tlEYFT00/XJq+tiAJe5E8ZKAIEWb3AyjzjCOwf3eWNqacikXxt2KHPOhD6NplVLdMYbNr4DMXwIMuwjz8J0C/bTkybDZlS7oUSyAdECarNQXiWwXQQDiyncX02co94fI0yoyBJ2LUNCFUCdXAY5O4tuNzeBBL+woG85eFW8jsDCoFSgu5gCWxnjU0N5T8FZbRNPxfITYz8XIqm0f6T8=
  on:
    tags: true
