sudo: false
language: python
python:
- '3.4'
env:
- TEST_SUITE='coverage run --source=pyega3 setup.py test'
install:
- pip install -r requirements.txt
- pip install python-coveralls
script:
- echo $TEST_SUITE
- echo $TEST_SUITE > test.sh
- bash test.sh
after_success:
- coverage report
- coveralls
- python setup.py sdist
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  user: ega
  password:
    secure: 0+GJHgstUHyZdL3o0Y8QnKiVnNGkHqaejW+GAAxxVBTZ1ZaMEZrBZuy3V4aYBNdXk/h8j7ZzL9OX/zDlEZkp+aqVWV6wNJy8TybYoypBYJ/JQbX0YMakDA2o21HU9gDwbyctA+CzVzTPK5VE7avXzWeXlritE7kAHuFItKuEgHVtZccqzVTg4Bww2hSjofvB9iuWuBk/QkM4167SbYciGbsXRa/V0ys6G853hiC3/VPwgMQbcd8PEzWza0WqG/5/1p+VUijxzeaRIY0O9BplVniF7t5NT0HV/6NAvTbPRB9cZJOTTsNS+pB0x3yTZFe1ohccZNq6UttQVYWQCJOzGy11aWqdVKK91lT4oRyyjME9UlOfy26xYTBJHHpK71cM3R0odb6CDy9VQNMQN1MoyYYoi4fBts4FchqEzt39iV1cdfiBP/OYkTggPti+WGLDl8uKncBeUC2a1O5QxCYq1eHQoEzDwKt7fIvXov6xnNrtsrDOVm1NOWUYzhNkEtes713Z0EGvU+O4X28dScEUo6+B5ROAWI6zxyFsiieh9g7hUQObYSOSNROJVpIKMKMxHFqXt3bovrlIZwJaiQSgDaPAgr/boZffGiadynC7DoyKftbmYNdZc3cwgeGZQoQxXT+4KTqjq4BDEaTE4UHxgYxkqu+Ua26/Dxhgiq4emoc=
  on:
    tags: true
